### ISSUE TITLE
Accessibility: can't get to credits using only keyboard

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cgradeff/emojisplosion-demo#2]
![Screenshot of the "Made with 💖 and React by Carly Gradeff" indicator](https://github.com/cgradeff/emojisplosion-site/assets/3335181/1e0ef0fe-68cb-494d-acd7-ee53a4c82199)

This friend can't be triggered using <kbd>Tab</kbd> navigation alone. I can only get to it by hovering with a mouse. 😞

**Comment by cgradeff** [comment]
fixed this by adding the credits to the footer (with no toggle) in the latest update!
