### ISSUE TITLE
Horizontal scrollbar on the main menu area

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cgradeff/emojisplosion-demo#3]
![A non-actionable horizontal scrollbar on emojisplosion.dev's right menu](https://github.com/cgradeff/emojisplosion-site/assets/3335181/b298ea14-217a-40ec-bf40-efd4e59cc3cb)

There's always a horizontal scrollbar in the menu, even if it's not needed. Maybe `overflow: auto` instead of `overflow: scroll`?

**Comment by cgradeff** [comment]
i can't see this issue on any of my browsers.. changed overflow to auto for the side bar tho so lmk if that fixed it!

**Comment by JoshuaKGoldberg** [comment]
Yup that got it for me, thanks!
