### ISSUE TITLE
Add an explainer of how to install/use emojisplosion

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cgradeff/emojisplosion-demo#6]
It'd be awesome if this site could include the [Emojisplosion _Usage_](https://github.com/cgradeff/emojisplosion-site) docs info on how to use the library.

(we were talking about this previously - just filing for tracking)

**Comment by CBID2** [comment]
I can help with that @cgradeff! :) I’ll do a rough draft on a Google doc and then copy and paste the information into a PR where you can review it! :)

**Comment by cgradeff** [comment]
@CBID2 I'm currently working on adding it but thank you so so much for offering! :)

**Comment by CBID2** [comment]
> @CBID2 I'm currently working on adding it but thank you so so much for offering! :)

Ok then I'll just add some suggestions when you do your PR. Sounds good @cgradeff! :)

**Comment by cgradeff** [comment]
Just added a docs page! (also want to add hash links eventually to link the configuration options to specific demos and vice versa)
